server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///D:/Inflearn Studies/learn-spring-cloud-git-local-repo
          uri: https://github.com/Jongwook-Seong/learn-spring-cloud-config.git
#          username: [my username] (private)
#          password: [my password] (private)